#!/usr/bin/env node

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import * as path from "node:path";
import * as os from "node:os";
import * as fs from "node:fs/promises";
import { spawn, exec } from "node:child_process";
import { promisify } from "node:util";
import simpleGit from "simple-git";
import { createWriteStream } from "node:fs";
import { pipeline } from "node:stream/promises";
import { Transform } from "node:stream";
import { createReadStream } from "node:fs";
import { Readable } from "node:stream";
import * as math from "mathjs";
import { ChartJSNodeCanvas } from "chartjs-node-canvas";
import * as canvas from "canvas";
import * as crypto from "node:crypto";

// Import utility modules
import { PLATFORM, IS_WINDOWS, IS_LINUX, IS_MACOS, IS_ANDROID, IS_IOS, IS_MOBILE, config, PROC_ALLOWLIST, MAX_BYTES, MOBILE_CONFIG, COMMAND_MAPPINGS } from "./config/environment.js";
import { ALLOWED_ROOTS, getPlatformCommand, getMobilePermissions, isMobileFeatureAvailable, getMobileDeviceInfo, getFileOperationCommand, getMobileProcessCommand, getMobileServiceCommand, getMobileNetworkCommand, getMobileStorageCommand, getMobileUserCommand } from "./utils/platform.js";
import { sanitizeCommand, isDangerousCommand, shouldPerformSecurityChecks } from "./utils/security.js";
import { ensureInsideRoot, limitString } from "./utils/fileSystem.js";
import { logger, logServerStart } from "./utils/logger.js";

// Global variables for enhanced features
let browserInstance: any = null;
let webSocketServer: any = null;
let expressServer: any = null;
let cronJobs: Map<string, any> = new Map();
let fileWatchers: Map<string, any> = new Map();
let apiCache: Map<string, any> = new Map();
let webhookEndpoints: Map<string, any> = new Map();

const execAsync = promisify(exec);

// Log server startup
logServerStart(PLATFORM);

// ===========================================
// CUSTOM SERVER: MCP God Mode - Complete
// ===========================================

const server = new McpServer({ name: "custom-mcp-server", version: "1.0.0" });

// Import and register selected tools
import { registerHealth } from "./tools/core/health";
import { registerSystemInfo } from "./tools/core/system_info";
import { registerFsList } from "./tools/file_system/fs_list";
import { registerFsReadText } from "./tools/file_system/fs_read_text";
import { registerFsWriteText } from "./tools/file_system/fs_write_text";
import { registerFsSearch } from "./tools/file_system/fs_search";
import { registerFileOps } from "./tools/file_system/file_ops";
import { registerFileWatcher } from "./tools/file_system/file_watcher";
import { registerProcRun } from "./tools/process/proc_run";
import { registerProcRunElevated } from "./tools/process/proc_run_elevated";
import { registerSystemRestore } from "./tools/system/system_restore";
import { registerElevatedPermissionsManager } from "./tools/system/elevated_permissions_manager";
import { registerCronJobManager } from "./tools/system/cron_job_manager";
import { registerSystemMonitor } from "./tools/system/system_monitor";
import { registerGitStatus } from "./tools/git/git_status";
import { registerWinServices } from "./tools/windows/win_services";
import { registerWinProcesses } from "./tools/windows/win_processes";
import { registerPacketSniffer } from "./tools/network/packet_sniffer";
import { registerPortScanner } from "./tools/network/port_scanner";
import { registerNetworkDiagnostics } from "./tools/network/network_diagnostics";
import { registerDownloadFile } from "./tools/utilities/download_file";
import { registerNetworkTrafficAnalyzer } from "./tools/network/network_traffic_analyzer";
import { registerIpGeolocation } from "./tools/network/ip_geolocation";
import { registerNetworkTriangulation } from "./tools/network/network_triangulation";
import { registerOsintReconnaissance } from "./tools/network/osint_reconnaissance";
import { registerLatencyGeolocation } from "./tools/network/latency_geolocation";
import { registerNetworkDiscovery } from "./tools/network/network_discovery";
import { registerVulnerabilityAssessment } from "./tools/network/vulnerability_assessment";
import { registerTrafficAnalysis } from "./tools/network/traffic_analysis";
import { registerNetworkUtilities } from "./tools/network/network_utilities";
import { registerSocialAccountRipper } from "./tools/network/social_account_ripper";
import { registerSocialAccountRipperModular } from "./tools/network/social_account_ripper_modular";
import { registerVulnerabilityScanner } from "./tools/security/vulnerability_scanner";
import { registerPasswordCracker } from "./tools/security/password_cracker";
import { registerExploitFramework } from "./tools/security/exploit_framework";
import { registerNetworkSecurity } from "./tools/security/network_security";
import { registerBlockchainSecurity } from "./tools/security/blockchain_security";
import { registerQuantumSecurity } from "./tools/security/quantum_security";
import { registerIotSecurity } from "./tools/security/iot_security";
import { registerSocialEngineering } from "./tools/security/social_engineering";
import { registerThreatIntelligence } from "./tools/security/threat_intelligence";
import { registerComplianceAssessment } from "./tools/security/compliance_assessment";
import { registerSocialNetworkRipper } from "./tools/social/social_network_ripper";
import { registerMetadataExtractor } from "./tools/security/metadata_extractor";
import { registerEncryptionTool } from "./tools/utilities/encryption_tool";
import { registerMalwareAnalysis } from "./tools/security/malware_analysis";
import { registerHackNetwork } from "./tools/penetration/hack_network";
import { registerSecurityTesting } from "./tools/penetration/security_testing";
import { registerNetworkPenetration } from "./tools/penetration/network_penetration";
import { registerPenetrationTestingToolkit } from "./tools/penetration/penetration_testing_toolkit";
import { registerSocialEngineeringToolkit } from "./tools/penetration/social_engineering_toolkit";
import { registerWifiSecurityToolkit } from "./tools/wireless/wifi_security_toolkit";
import { registerWifiHacking } from "./tools/wireless/wifi_hacking";
import { registerWirelessSecurity } from "./tools/wireless/wireless_security";
import { registerWirelessNetworkScanner } from "./tools/wireless/wireless_network_scanner";
import { registerBluetoothSecurityToolkit } from "./tools/bluetooth/bluetooth_security_toolkit";
import { registerBluetoothHacking } from "./tools/bluetooth/bluetooth_hacking";
import { registerBluetoothDeviceManager } from "./tools/bluetooth/bluetooth_device_manager";
import { registerSdrSecurityToolkit } from "./tools/radio/sdr_security_toolkit";
import { registerRadioSecurity } from "./tools/radio/radio_security";
import { registerSignalAnalysis } from "./tools/radio/signal_analysis";
import { registerWebScraper } from "./tools/web/web_scraper";
import { registerBrowserControl } from "./tools/web/browser_control";
import { registerWebAutomation } from "./tools/web/web_automation";
import { registerWebhookManager } from "./tools/web/webhook_manager";
import { registerUniversalBrowserOperator } from "./tools/web/universal_browser_operator";
import { registerWebSearch } from "./tools/web/web_search";
import { registerCaptchaDefeating } from "./tools/web/captcha_defeating";
import { registerFormCompletion } from "./tools/web/form_completion";
import { registerSendEmail } from "./tools/email/send_email";
import { registerReadEmails } from "./tools/email/read_emails";
import { registerParseEmail } from "./tools/email/parse_email";
import { registerDeleteEmails } from "./tools/email/delete_emails";
import { registerSortEmails } from "./tools/email/sort_emails";
import { registerManageEmailAccounts } from "./tools/email/manage_email_accounts";
import { registerVideoEditing } from "./tools/media/video_editing";
import { registerOcrTool } from "./tools/media/ocr_tool";
import { registerImageEditing } from "./tools/media/image_editing";
import { registerAudioEditing } from "./tools/audio_editing/index";
import { registerScreenshot } from "./tools/screenshot/index";
import { registerMobileDeviceInfo } from "./tools/mobile/mobile_device_info";
import { registerMobileFileOps } from "./tools/mobile/mobile_file_ops";
import { registerMobileSystemTools } from "./tools/mobile/mobile_system_tools";
import { registerMobileHardware } from "./tools/mobile/mobile_hardware";
import { registerMobileDeviceManagement } from "./tools/mobile/mobile_device_management";
import { registerMobileAppAnalyticsToolkit } from "./tools/mobile/mobile_app_analytics_toolkit";
import { registerMobileAppDeploymentToolkit } from "./tools/mobile/mobile_app_deployment_toolkit";
import { registerMobileAppOptimizationToolkit } from "./tools/mobile/mobile_app_optimization_toolkit";
import { registerMobileAppSecurityToolkit } from "./tools/mobile/mobile_app_security_toolkit";
import { registerMobileAppMonitoringToolkit } from "./tools/mobile/mobile_app_monitoring_toolkit";
import { registerMobileAppPerformanceToolkit } from "./tools/mobile/mobile_app_performance_toolkit";
import { registerMobileAppTestingToolkit } from "./tools/mobile/mobile_app_testing_toolkit";
import { registerMobileNetworkAnalyzer } from "./tools/mobile/mobile_network_analyzer";
import { registerVmManagement } from "./tools/virtualization/vm_management";
import { registerDockerManagement } from "./tools/virtualization/docker_management";
import { registerCalculator } from "./tools/utilities/calculator";
import { registerDiceRolling } from "./tools/utilities/dice_rolling";
import { registerMathCalculate } from "./tools/utilities/math_calculate";
import { registerDataAnalysis } from "./tools/utilities/data_analysis";
import { registerMachineLearning } from "./tools/utilities/machine_learning";
import { registerChartGenerator } from "./tools/utilities/chart_generator";
import { registerTextProcessor } from "./tools/utilities/text_processor";
import { registerPasswordGenerator } from "./tools/utilities/password_generator";
import { registerDataAnalyzer } from "./tools/utilities/data_analyzer";
import { registerCloudSecurity } from "./tools/cloud/cloud_security";
import { registerCloudInfrastructureManager } from "./tools/cloud/cloud_infrastructure_manager";
import { registerCloudSecurityToolkit } from "./tools/cloud/cloud_security_toolkit";
import { registerForensicsAnalysis } from "./tools/forensics/forensics_analysis";
import { registerForensicsToolkit } from "./tools/forensics/forensics_toolkit";
import { registerMalwareAnalysisToolkit } from "./tools/forensics/malware_analysis_toolkit";
import { registerToolDiscovery } from "./tools/discovery/tool_discovery";
import { registerExploreCategories } from "./tools/discovery/explore_categories";

// Register all selected tools
registerHealth(server);
registerSystemInfo(server);
registerFsList(server);
registerFsReadText(server);
registerFsWriteText(server);
registerFsSearch(server);
registerFileOps(server);
registerFileWatcher(server);
registerProcRun(server);
registerProcRunElevated(server);
registerSystemRestore(server);
registerElevatedPermissionsManager(server);
registerCronJobManager(server);
registerSystemMonitor(server);
registerGitStatus(server);
registerWinServices(server);
registerWinProcesses(server);
registerPacketSniffer(server);
registerPortScanner(server);
registerNetworkDiagnostics(server);
registerDownloadFile(server);
registerNetworkTrafficAnalyzer(server);
registerIpGeolocation(server);
registerNetworkTriangulation(server);
registerOsintReconnaissance(server);
registerLatencyGeolocation(server);
registerNetworkDiscovery(server);
registerVulnerabilityAssessment(server);
registerTrafficAnalysis(server);
registerNetworkUtilities(server);
registerSocialAccountRipper(server);
registerSocialAccountRipperModular(server);
registerVulnerabilityScanner(server);
registerPasswordCracker(server);
registerExploitFramework(server);
registerNetworkSecurity(server);
registerBlockchainSecurity(server);
registerQuantumSecurity(server);
registerIotSecurity(server);
registerSocialEngineering(server);
registerThreatIntelligence(server);
registerComplianceAssessment(server);
registerSocialNetworkRipper(server);
registerMetadataExtractor(server);
registerEncryptionTool(server);
registerMalwareAnalysis(server);
registerHackNetwork(server);
registerSecurityTesting(server);
registerNetworkPenetration(server);
registerPenetrationTestingToolkit(server);
registerSocialEngineeringToolkit(server);
registerWifiSecurityToolkit(server);
registerWifiHacking(server);
registerWirelessSecurity(server);
registerWirelessNetworkScanner(server);
registerBluetoothSecurityToolkit(server);
registerBluetoothHacking(server);
registerBluetoothDeviceManager(server);
registerSdrSecurityToolkit(server);
registerRadioSecurity(server);
registerSignalAnalysis(server);
registerWebScraper(server);
registerBrowserControl(server);
registerWebAutomation(server);
registerWebhookManager(server);
registerUniversalBrowserOperator(server);
registerWebSearch(server);
registerCaptchaDefeating(server);
registerFormCompletion(server);
registerSendEmail(server);
registerReadEmails(server);
registerParseEmail(server);
registerDeleteEmails(server);
registerSortEmails(server);
registerManageEmailAccounts(server);
registerVideoEditing(server);
registerOcrTool(server);
registerImageEditing(server);
registerAudioEditing(server);
registerScreenshot(server);
registerMobileDeviceInfo(server);
registerMobileFileOps(server);
registerMobileSystemTools(server);
registerMobileHardware(server);
registerMobileDeviceManagement(server);
registerMobileAppAnalyticsToolkit(server);
registerMobileAppDeploymentToolkit(server);
registerMobileAppOptimizationToolkit(server);
registerMobileAppSecurityToolkit(server);
registerMobileAppMonitoringToolkit(server);
registerMobileAppPerformanceToolkit(server);
registerMobileAppTestingToolkit(server);
registerMobileNetworkAnalyzer(server);
registerVmManagement(server);
registerDockerManagement(server);
registerCalculator(server);
registerDiceRolling(server);
registerMathCalculate(server);
registerDataAnalysis(server);
registerMachineLearning(server);
registerChartGenerator(server);
registerTextProcessor(server);
registerPasswordGenerator(server);
registerDataAnalyzer(server);
registerCloudSecurity(server);
registerCloudInfrastructureManager(server);
registerCloudSecurityToolkit(server);
registerForensicsAnalysis(server);
registerForensicsToolkit(server);
registerMalwareAnalysisToolkit(server);
registerToolDiscovery(server);
registerExploreCategories(server);

// ===========================================
// START THE SERVER
// ===========================================

const transport = new StdioServerTransport();
server.connect(transport);

console.log(`MCP God Mode - Complete started with 112 tools`);
console.log('Available tools:', 'health, system_info, fs_list, fs_read_text, fs_write_text, fs_search, file_ops, file_watcher, proc_run, proc_run_elevated, system_restore, elevated_permissions_manager, cron_job_manager, system_monitor, git_status, win_services, win_processes, packet_sniffer, port_scanner, network_diagnostics, download_file, network_traffic_analyzer, ip_geolocation, network_triangulation, osint_reconnaissance, latency_geolocation, network_discovery, vulnerability_assessment, traffic_analysis, network_utilities, social_account_ripper, social_account_ripper_modular, vulnerability_scanner, password_cracker, exploit_framework, network_security, blockchain_security, quantum_security, iot_security, social_engineering, threat_intelligence, compliance_assessment, social_network_ripper, metadata_extractor, encryption_tool, malware_analysis, hack_network, security_testing, network_penetration, penetration_testing_toolkit, social_engineering_toolkit, wifi_security_toolkit, wifi_hacking, wireless_security, wireless_network_scanner, bluetooth_security_toolkit, bluetooth_hacking, bluetooth_device_manager, sdr_security_toolkit, radio_security, signal_analysis, web_scraper, browser_control, web_automation, webhook_manager, universal_browser_operator, web_search, captcha_defeating, form_completion, send_email, read_emails, parse_email, delete_emails, sort_emails, manage_email_accounts, video_editing, ocr_tool, image_editing, audio_editing, screenshot, mobile_device_info, mobile_file_ops, mobile_system_tools, mobile_hardware, mobile_device_management, mobile_app_analytics_toolkit, mobile_app_deployment_toolkit, mobile_app_optimization_toolkit, mobile_app_security_toolkit, mobile_app_monitoring_toolkit, mobile_app_performance_toolkit, mobile_app_testing_toolkit, mobile_network_analyzer, vm_management, docker_management, calculator, dice_rolling, math_calculate, data_analysis, machine_learning, chart_generator, text_processor, password_generator, data_analyzer, cloud_security, cloud_infrastructure_manager, cloud_security_toolkit, forensics_analysis, forensics_toolkit, malware_analysis_toolkit, tool_discovery, explore_categories');
